### ISSUE TITLE
worker monitor celery v5 change

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisPlatform#452]
worker has no flag -A, needs to be set on the celery level

```celery worker -A src.server.oasisapi --loglevel=INFO
You are using `-A` as an option of the worker sub-command:
celery worker -A celeryapp <...>

The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery -A celeryapp worker <...>```

**Comment by benhayes21** [comment]
fixed already.

**Comment by dholdaway** [comment]
hello, how and where was this fixed. I am still seeing this error.
